# Preprocessing configuration file ------------------------------------------------

glob:
  base_dir: /wshare/travail/bdgrid2/EXTRACTION/Deep_learning/orthophotos/QC_Chaudiere-Etchemin/ImagerieChaudiereEtchemins/Mosa15rvb1630_15cm_Rvb/Mtm7/geotiff
  out_path: /wshare/travail/bdgrid2/EXTRACTION/Deep_learning/orthophotos/QC_Chaudiere-Etchemin/ImagerieChaudiereEtchemins/Mosa15rvb1630_15cm_Rvb/Mtm7
  out_tif_name: 2018_CMQ_15cm

process:
  overwrite: False # if True, overwrites existing output file
  dry_run: False

list_img:
  keep_only: uint8 # all, uint8, uint16, singleband
