# Preprocessing configuration file ------------------------------------------------

glob:
  base_dir: C:\Users\maturgeo\Documents\Travail\image_preprocessing\subset_2
  mul_pan_glob: # See README
    1: ["**/*_MUL/*-M*_P00?", "../*_PAN"]
    2: ["**/*_MSI*", "."]
  mul_pan_str: # See README
    1: ["-M", "-P"]
    2: ["_MSI", "_PAN"]
  psh_glob: ["**/*_PSH/*_P00?"] # See README
  extensions: ["tif", "ntf"] # list of all possible extensions the raster files may have. Case-sensitive on Linux.
  out_csv: 'logs/glob_metadata.csv' # Output csv for glob process

pansharp:
  input_csv:  # csv from glob process, if glob was done as separate step.
  method: otb-bayes # otb-lmvm, otb-bayes, simple_brovey, brovey, simple_mean, esri, hsv
  to_8bit: True # create a uint8 version if pansharp is uint16.
  trim: 0 # Quantiles to cut from histogram low/high values.
  # cog: False # Create and validate COG from pansharp.
  # cog_delete_source: False  # if True, deletes source image after coggifying process is done
  overwrite: False # if True, overwrites existing output file
  dry_run: False
  log_csv: # "pansharp_log.csv" # Output csv for pansharp process